// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shahmati.Infrastructure.Postgres;

#nullable disable

namespace Shahmati.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ShahmatiDbContext))]
    partial class ShahmatiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shahmati.Domain.Games", b =>
                {
                    b.Property<Guid>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Hodie", "Shahmati.Domain.Games.Hodie#Coordinates", b1 =>
                        {
                            b1.Property<char>("bukva")
                                .HasColumnType("character(1)")
                                .HasColumnName("hodie_bukva");

                            b1.Property<short>("integer")
                                .HasColumnType("smallint")
                                .HasColumnName("hodie_integer");
                        });

                    b.HasKey("GamesId");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
