// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shahmati.Infrastructure.Postgres;

#nullable disable

namespace Shahmati.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(ShahmatiDbContext))]
    partial class ShahmatiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shahmati.Domain.Coordinates", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("Bukva")
                        .HasColumnType("character(1)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<short>("Integer")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Shahmati.Domain.Games", b =>
                {
                    b.Property<Guid>("GamesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("GamesId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Shahmati.Domain.Player", b =>
                {
                    b.Property<Guid>("PlayersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<int>("Reyting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayersId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Shahmati.Domain.PlayrsThisGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ThisGameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId");

                    b.HasIndex("ThisGameId");

                    b.ToTable("PlayrsThisGame");
                });

            modelBuilder.Entity("Shahmati.Domain.Coordinates", b =>
                {
                    b.HasOne("Shahmati.Domain.Games", "Game")
                        .WithMany("CoordinatesCollection")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Shahmati.Domain.PlayrsThisGame", b =>
                {
                    b.HasOne("Shahmati.Domain.Player", "PlayerEntity")
                        .WithMany("Games")
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shahmati.Domain.Games", "ThisGame")
                        .WithMany("Players")
                        .HasForeignKey("ThisGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerEntity");

                    b.Navigation("ThisGame");
                });

            modelBuilder.Entity("Shahmati.Domain.Games", b =>
                {
                    b.Navigation("CoordinatesCollection");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("Shahmati.Domain.Player", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
